"""Quiz generation service using DeepSeek.

Two-layer structure:
- Layer 1: Question bank (quiz_bank) — generated by AI, cached by content_hash
- Layer 2: Quiz attempt — sampled from bank, submitted by user

Stores results in Note.vocabulary with kind="quiz_bank" and kind="quiz".
"""

import json
import logging
import random
import threading
import time
import uuid
from datetime import datetime, timezone
from typing import Optional

from openai import OpenAI

from app.config import DEEPSEEK_API_KEY, DEEPSEEK_BASE_URL, DEEPSEEK_MODEL
from app.models import Note, Session, Notebook, User, Task
from sqlalchemy.orm import Session as DBSessionType
from app.core.database import SessionLocal
from app.services.prompt_loader import load_prompt
from app.services.vector_service import _compute_session_content_hash


logger = logging.getLogger(__name__)

TASK_TYPE = "quiz_bank_generate"
ACTIVE_TASK_STATUSES = {"pending", "running"}
QUESTIONS_PER_QUIZ = 10


# ── Vocabulary helpers: quiz_bank ──

def _get_quiz_bank_from_vocabulary(note: Note) -> Optional[dict]:
    """Read the quiz_bank entry from note.vocabulary."""
    if not isinstance(note.vocabulary, list):
        return None
    for item in note.vocabulary:
        if isinstance(item, dict) and item.get("kind") == "quiz_bank":
            return item
    return None


def _set_quiz_bank_in_vocabulary(note: Note, bank_data: dict, content_hash: str):
    """Set or replace the quiz_bank entry in note.vocabulary."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = [item for item in existing if not (isinstance(item, dict) and item.get("kind") == "quiz_bank")]
    next_items.append({
        "kind": "quiz_bank",
        "content_hash": content_hash,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "questions": bank_data["questions"],
    })
    note.vocabulary = next_items


# ── Vocabulary helpers: quiz attempts ──

def _get_quizzes_from_vocabulary(note: Note) -> list[dict]:
    """Read all quiz attempt entries from note.vocabulary."""
    if not isinstance(note.vocabulary, list):
        return []
    return [
        item for item in note.vocabulary
        if isinstance(item, dict) and item.get("kind") == "quiz"
    ]


def _add_quiz_to_vocabulary(note: Note, quiz_entry: dict):
    """Add a quiz attempt entry to note.vocabulary."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = list(existing)
    next_items.append(quiz_entry)
    note.vocabulary = next_items


def _remove_quiz_from_vocabulary(note: Note, quiz_id: str):
    """Remove a specific quiz attempt from note.vocabulary by quiz_id."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = [
        item for item in existing
        if not (isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id)
    ]
    note.vocabulary = next_items


def _get_quiz_from_vocabulary(note: Note, quiz_id: str) -> Optional[dict]:
    """Read a specific quiz attempt from note.vocabulary by quiz_id."""
    if not isinstance(note.vocabulary, list):
        return None
    for item in note.vocabulary:
        if isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id:
            return item
    return None


def _update_quiz_in_vocabulary(note: Note, quiz_id: str, updated_entry: dict):
    """Replace a quiz entry in vocabulary (for saving submissions)."""
    existing = note.vocabulary if isinstance(note.vocabulary, list) else []
    next_items = []
    for item in existing:
        if isinstance(item, dict) and item.get("kind") == "quiz" and item.get("quiz_id") == quiz_id:
            next_items.append(updated_entry)
        else:
            next_items.append(item)
    note.vocabulary = next_items


# ── Content extraction ──

def _extract_content_for_prompt(note: Note) -> str:
    """Extract all note content into a single text for the AI prompt."""
    parts = []

    layout_blocks = note.layout_blocks
    if layout_blocks and isinstance(layout_blocks, list):
        for block in layout_blocks:
            if not isinstance(block, dict):
                continue
            btype = block.get("type", "")
            content = block.get("content", "")
            page = block.get("page")
            title = block.get("title", "")

            if btype == "transcript" and content:
                parts.append(f"[转写] {content.strip()}")
            elif btype == "note" and content:
                parts.append(f"[笔记] {content.strip()}")
            elif btype == "ppt":
                ppt_text = ""
                if title:
                    ppt_text += title + " "
                if content:
                    ppt_text += content + " "
                if ppt_text.strip():
                    parts.append(f"[PPT第{page or '?'}页] {ppt_text.strip()}")

    if not parts and note.content:
        parts.append(note.content.strip())

    if note.transcript and isinstance(note.transcript, list):
        transcript_text = " ".join(
            chunk.get("text", "")
            for chunk in sorted(note.transcript, key=lambda x: x.get("chunk_index", 0))
            if isinstance(chunk, dict)
        ).strip()
        if transcript_text and not any("[转写]" in p for p in parts):
            parts.append(f"[转写] {transcript_text}")

    if note.ppt_images and isinstance(note.ppt_images, list):
        for ppt_data in note.ppt_images:
            if not isinstance(ppt_data, dict):
                continue
            for slide in ppt_data.get("slides", []):
                if not isinstance(slide, dict):
                    continue
                slide_text = slide.get("text", "")
                if slide_text:
                    parts.append(f"[PPT第{slide.get('page', '?')}页] {slide_text.strip()}")

    return "\n\n".join(parts)


# ── Session ownership ──

def _get_session_for_user(session_id: str, user: User, db: DBSessionType) -> Session | None:
    return db.query(Session).filter(
        Session.id == session_id
    ).join(Notebook).filter(Notebook.user_id == user.id).first()


# ── Normalization / validation ──

VALID_OPTION_IDS = {"A", "B", "C", "D"}
VALID_SOURCE_TYPES = {"transcript", "note", "ppt"}


def _normalize_option(option: dict) -> Optional[dict]:
    if not isinstance(option, dict):
        return None
    opt_id = option.get("id")
    text = option.get("text")
    if not opt_id or not text:
        return None
    opt_id = str(opt_id).upper()
    if opt_id not in VALID_OPTION_IDS:
        return None
    return {
        "id": opt_id,
        "text": str(text),
        "explanation": str(option.get("explanation", "")),
    }


def _normalize_question(question: dict) -> Optional[dict]:
    if not isinstance(question, dict):
        return None
    q_id = question.get("id")
    q_text = question.get("question")
    if not q_id or not q_text:
        return None

    raw_options = question.get("options", [])
    if not isinstance(raw_options, list):
        return None

    options = []
    for opt in raw_options:
        normalized = _normalize_option(opt)
        if normalized:
            options.append(normalized)

    if len(options) != 4:
        return None
    option_ids = {o["id"] for o in options}
    if option_ids != VALID_OPTION_IDS:
        return None

    answer = str(question.get("answer", "")).upper()
    if answer not in option_ids:
        return None

    raw_source = question.get("source", {})
    if not isinstance(raw_source, dict):
        raw_source = {}
    source_type = raw_source.get("source_type", "note")
    if source_type not in VALID_SOURCE_TYPES:
        source_type = "note"
    page = raw_source.get("page")
    if not isinstance(page, int):
        page = None

    return {
        "id": str(q_id),
        "question": str(q_text),
        "options": options,
        "answer": answer,
        "explanation": str(question.get("explanation", "")),
        "source": {
            "source_type": source_type,
            "snippet": str(raw_source.get("snippet", "")),
            "page": page,
        },
    }


def normalize_quiz_data(data: dict) -> dict:
    """Normalize and validate the quiz bank data structure."""
    if not isinstance(data, dict):
        raise ValueError("AI 返回的 JSON 不是对象")

    raw_questions = data.get("questions", [])
    if not isinstance(raw_questions, list):
        raise ValueError("AI 返回的 JSON 中 questions 不是列表")

    questions = []
    for q in raw_questions:
        normalized = _normalize_question(q)
        if normalized:
            questions.append(normalized)

    if not questions:
        raise ValueError("AI 返回的 JSON 中没有有效的题目")

    return {
        "title": str(data.get("title", "本节课测验")),
        "questions": questions,
    }


# ── Async task helpers ──

def _get_latest_task(session_id: str, db: DBSessionType) -> Task | None:
    return db.query(Task).filter(
        Task.session_id == session_id,
        Task.task_type == TASK_TYPE,
    ).order_by(Task.created_at.desc()).first()


def _get_active_task(session_id: str, db: DBSessionType) -> Task | None:
    return db.query(Task).filter(
        Task.session_id == session_id,
        Task.task_type == TASK_TYPE,
        Task.status.in_(ACTIVE_TASK_STATUSES),
    ).order_by(Task.created_at.desc()).first()


def _task_payload(task: Task | None) -> dict:
    if not task:
        return {}
    return {
        "task_id": task.id,
        "progress": float(task.progress or 0.0),
        "error": task.error_message,
    }


# ── Core: generate question bank (synchronous, called from thread) ──

def _generate_question_bank_sync(session_id: str, user: User, db: DBSessionType) -> dict:
    """Call DeepSeek to generate a question bank. Returns normalized bank data."""
    if not DEEPSEEK_API_KEY:
        raise ValueError("未配置 DEEPSEEK_API_KEY，无法生成测验")

    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")

    content_text = _extract_content_for_prompt(note)
    if not content_text.strip():
        raise ValueError("No indexable content in note")

    keywords = ", ".join(session.keywords) if session.keywords else "无"
    prompt_template = load_prompt("quiz_bank")
    prompt = prompt_template.render(
        title=session.title or "未命名课次",
        keywords=keywords,
        content=content_text[:8000],
    )

    client = OpenAI(api_key=DEEPSEEK_API_KEY, base_url=DEEPSEEK_BASE_URL)
    try:
        response = client.chat.completions.create(
            model=DEEPSEEK_MODEL,
            messages=[
                {"role": "system", "content": prompt_template.system},
                {"role": "user", "content": prompt},
            ],
            temperature=0.4,
            max_tokens=8000,
        )
    except Exception as e:
        error_msg = str(e)
        if "timeout" in error_msg.lower() or "timed out" in error_msg.lower():
            raise ValueError("题库生成失败: DeepSeek 请求超时，请稍后重试")
        raise ValueError(f"题库生成失败: {error_msg}")

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences
    if raw.startswith("```"):
        lines = raw.split("\n")
        lines = [l for l in lines if not l.startswith("```")]
        raw = "\n".join(lines)

    try:
        bank_data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"AI 返回的 JSON 格式无效: {e}")

    bank_data = normalize_quiz_data(bank_data)

    # Save bank to vocabulary
    content_hash = _compute_session_content_hash(note)
    _set_quiz_bank_in_vocabulary(note, bank_data, content_hash)
    db.commit()

    return bank_data


# ── Async task runner ──

def _run_quiz_bank_task(task_id: str, session_id: str, user_id: str):
    db = SessionLocal()
    started = time.monotonic()
    try:
        task = db.query(Task).filter(Task.id == task_id).first()
        user = db.query(User).filter(User.id == user_id).first()
        if not task or not user:
            return

        task.status = "running"
        task.progress = 0.1
        task.error_message = None
        db.commit()

        _generate_question_bank_sync(session_id, user, db)

        task = db.query(Task).filter(Task.id == task_id).first()
        if task:
            task.status = "success"
            task.progress = 1.0
            task.error_message = None
            db.commit()
        logger.info(
            "quiz_bank_task_success task_id=%s session_id=%s elapsed_ms=%s",
            task_id, session_id, int((time.monotonic() - started) * 1000),
        )
    except Exception as e:
        db.rollback()
        task = db.query(Task).filter(Task.id == task_id).first()
        if task:
            task.status = "error"
            task.progress = 1.0
            task.error_message = str(e)
            db.commit()
        logger.exception(
            "quiz_bank_task_failed task_id=%s session_id=%s",
            task_id, session_id,
        )
    finally:
        db.close()


# ── Bank status ──

def get_bank_status(session_id: str, user: User, db: DBSessionType) -> dict:
    """Get question bank status for a session."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    has_content = bool(note and (note.content or note.transcript or note.ppt_images or note.layout_blocks))

    if not has_content:
        return {"session_id": session_id, "status": "empty", "question_count": 0, "task_id": None, "progress": 0, "error": None}

    bank_entry = _get_quiz_bank_from_vocabulary(note) if note else None
    active_task = _get_active_task(session_id, db)

    if active_task:
        return {
            "session_id": session_id,
            "status": "generating",
            "question_count": len(bank_entry.get("questions", [])) if bank_entry else 0,
            **_task_payload(active_task),
        }

    if not bank_entry:
        latest_task = _get_latest_task(session_id, db)
        if latest_task and latest_task.status == "error":
            return {
                "session_id": session_id,
                "status": "error",
                "question_count": 0,
                **_task_payload(latest_task),
            }
        return {"session_id": session_id, "status": "not_generated", "question_count": 0, "task_id": None, "progress": 0, "error": None}

    # Check stale
    current_hash = _compute_session_content_hash(note)
    bank_hash = bank_entry.get("content_hash", "")
    if current_hash != bank_hash:
        return {
            "session_id": session_id,
            "status": "stale",
            "question_count": len(bank_entry.get("questions", [])),
            "task_id": None,
            "progress": 0,
            "error": None,
        }

    return {
        "session_id": session_id,
        "status": "ready",
        "question_count": len(bank_entry.get("questions", [])),
        "task_id": None,
        "progress": 1.0,
        "error": None,
    }


# ── Start/rebuild bank ──

def start_bank_generation(session_id: str, user: User, db: DBSessionType, force: bool = False) -> dict:
    """Start or reuse an async question bank generation task.

    If force=True, ignore the "ready" status and start a new task (for manual rebuild).
    If force=False, return ready status if bank is already valid.
    Always reuses an active (pending/running) task regardless of force.
    """
    if not DEEPSEEK_API_KEY:
        raise ValueError("未配置 DEEPSEEK_API_KEY，无法生成测验")

    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")
    content_text = _extract_content_for_prompt(note)
    if not content_text.strip():
        raise ValueError("No indexable content in note")

    # Always reuse active task if one exists
    active_task = _get_active_task(session_id, db)
    if active_task:
        return {
            "session_id": session_id,
            "status": "generating",
            "question_count": 0,
            **_task_payload(active_task),
        }

    # If not forced and bank is ready, return it
    if not force:
        bank_status = get_bank_status(session_id, user, db)
        if bank_status["status"] == "ready":
            return bank_status

    # Create new task
    task = Task(
        session_id=session_id,
        task_type=TASK_TYPE,
        status="pending",
        progress=0.0,
        error_message=None,
    )
    db.add(task)
    db.commit()
    db.refresh(task)

    thread = threading.Thread(
        target=_run_quiz_bank_task,
        args=(task.id, session_id, user.id),
        daemon=True,
    )
    thread.start()
    logger.info(
        "quiz_bank_task_started task_id=%s session_id=%s user_id=%s",
        task.id, session_id, user.id,
    )

    return {
        "session_id": session_id,
        "status": "generating",
        "question_count": 0,
        **_task_payload(task),
    }


# ── Generate quiz attempt (from bank, no AI call) ──

def generate_quiz(session_id: str, user: User, db: DBSessionType) -> dict:
    """Generate a quiz attempt by sampling from the question bank.

    If bank is not ready, returns status info so the frontend can trigger bank generation.
    Does NOT call AI — only samples from existing bank.
    """
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("No note content found")

    bank_entry = _get_quiz_bank_from_vocabulary(note)
    if not bank_entry or not bank_entry.get("questions"):
        # Need to generate bank first — return status so frontend can trigger
        return {"status": "need_bank", "message": "请先生成题库"}

    # Check stale
    current_hash = _compute_session_content_hash(note)
    if current_hash != bank_entry.get("content_hash", ""):
        return {"status": "stale", "message": "笔记内容已变化，请重新生成题库"}

    # Sample questions from bank
    all_questions = bank_entry["questions"]
    count = min(QUESTIONS_PER_QUIZ, len(all_questions))
    sampled = random.sample(all_questions, count)

    quiz_id = str(uuid.uuid4())

    # Save full question snapshot in the attempt so it's immune to bank rebuilds.
    # The snapshot includes answers; we strip them when returning to the frontend.
    questions_snapshot = sampled

    quiz_entry = {
        "kind": "quiz",
        "quiz_id": quiz_id,
        "bank_hash": bank_entry.get("content_hash", ""),
        "questions_snapshot": questions_snapshot,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "submission": None,
    }
    _add_quiz_to_vocabulary(note, quiz_entry)
    db.commit()

    # Return questions WITHOUT answers for the taking-quiz view
    safe_questions = []
    for q in sampled:
        safe_questions.append({
            "id": q["id"],
            "question": q["question"],
            "options": [{"id": o["id"], "text": o["text"]} for o in q.get("options", [])],
        })

    return {
        "quiz_id": quiz_id,
        "title": "本节课测验",
        "questions": safe_questions,
    }


# ── List quizzes (without answers) ──

def get_session_quizzes(session_id: str, user: User, db: DBSessionType) -> list[dict]:
    """Return list of all quiz attempts for a session, without answers."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        return []

    quizzes = _get_quizzes_from_vocabulary(note)
    result = []
    for entry in quizzes:
        snapshot = entry.get("questions_snapshot", [])
        submission = entry.get("submission")

        # Build safe questions (no answers)
        safe_questions = []
        for q in snapshot:
            safe_questions.append({
                "id": q.get("id"),
                "question": q.get("question"),
                "options": [{"id": o.get("id"), "text": o.get("text")} for o in q.get("options", [])],
            })

        score_summary = None
        if submission:
            score_summary = {
                "score": submission.get("score", 0),
                "total": submission.get("total", 0),
                "percentage": submission.get("percentage", 0),
            }

        result.append({
            "quiz_id": entry.get("quiz_id"),
            "title": "本节课测验",
            "question_count": len(snapshot),
            "questions": safe_questions,
            "generated_at": entry.get("generated_at"),
            "submitted": submission is not None,
            "score": score_summary,
        })

    return result


# ── Quiz detail ──

def get_quiz_detail(session_id: str, quiz_id: str, user: User, db: DBSessionType) -> dict:
    """Return quiz detail. If not submitted, strip answers. If submitted, return full detail."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("Quiz not found")

    entry = _get_quiz_from_vocabulary(note, quiz_id)
    if not entry:
        raise ValueError("Quiz not found")

    snapshot = entry.get("questions_snapshot", [])
    submission = entry.get("submission")

    if submission:
        # Submitted — return full detail with answers and explanations
        return {
            "quiz_id": entry.get("quiz_id"),
            "title": "本节课测验",
            "questions": snapshot,
            "generated_at": entry.get("generated_at"),
            "submission": submission,
        }
    else:
        # Not submitted — strip answers
        safe_questions = []
        for q in snapshot:
            safe_questions.append({
                "id": q.get("id"),
                "question": q.get("question"),
                "options": [{"id": o.get("id"), "text": o.get("text")} for o in q.get("options", [])],
            })

        return {
            "quiz_id": entry.get("quiz_id"),
            "title": "本节课测验",
            "questions": safe_questions,
            "generated_at": entry.get("generated_at"),
            "submission": None,
        }


# ── Submit quiz answers ──

def submit_quiz_answers(session_id: str, quiz_id: str, user: User, db: DBSessionType, answers: dict) -> dict:
    """Submit answers for a quiz attempt. Calculate score using bank answers."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if not note:
        raise ValueError("Quiz not found")

    entry = _get_quiz_from_vocabulary(note, quiz_id)
    if not entry:
        raise ValueError("Quiz not found")

    # If already submitted, return existing results
    if entry.get("submission"):
        sub = entry["submission"]
        return {
            "score": sub.get("score", 0),
            "total": sub.get("total", 0),
            "percentage": sub.get("percentage", 0),
            "results": sub.get("results", []),
        }

    # Get answers from snapshot (immune to bank rebuilds)
    snapshot = entry.get("questions_snapshot", [])

    correct_count = 0
    results = []
    for q in snapshot:
        qid = q.get("id")
        correct_answer = q.get("answer", "")
        selected = answers.get(qid, "")
        is_correct = selected == correct_answer
        if is_correct:
            correct_count += 1

        results.append({
            "question_id": qid,
            "correct": is_correct,
            "selected": selected,
            "answer": correct_answer,
            "explanation": q.get("explanation", ""),
        })

    total = len(snapshot)
    percentage = round(correct_count / total * 100, 1) if total > 0 else 0

    # Save submission
    updated_entry = dict(entry)
    updated_entry["submission"] = {
        "answers": answers,
        "score": correct_count,
        "total": total,
        "percentage": percentage,
        "results": results,
        "submitted_at": datetime.now(timezone.utc).isoformat(),
    }
    _update_quiz_in_vocabulary(note, quiz_id, updated_entry)
    db.commit()

    return {
        "score": correct_count,
        "total": total,
        "percentage": percentage,
        "results": results,
    }


# ── Delete quiz attempt ──

def delete_quiz(session_id: str, quiz_id: str, user: User, db: DBSessionType) -> dict:
    """Delete a specific quiz attempt (not the bank)."""
    session = _get_session_for_user(session_id, user, db)
    if not session:
        raise ValueError("Session not found or access denied")

    note = db.query(Note).filter(Note.session_id == session_id).first()
    if note:
        _remove_quiz_from_vocabulary(note, quiz_id)
        db.commit()

    return {"session_id": session_id, "quiz_id": quiz_id, "status": "deleted"}
