"""add_user_security_question

Revision ID: c20d4ecdf67d
Revises: 360f283093ee
Create Date: 2026-06-09 11:17:56.141720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20d4ecdf67d'
down_revision: Union[str, Sequence[str], None] = '360f283093ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('share_view_count',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text('0'))
    op.add_column('users', sa.Column('security_question', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('security_answer_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer_hash')
    op.drop_column('users', 'security_question')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('share_view_count',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
